#!/bin/bash

#strict mode
set -euo pipefail
IFS=$'\n\t'

#make sure system is up to date
sudo apt-get update
sudo apt-get upgrade -y

#install pip
sudo apt-get install python-pip -y

#install python virtualenv
sudo apt-get install python-virtualenv -y

#create virtualenv
virtualenv ../plates_env

#activate virtualenv
PS1="" source ../plates_env/bin/activate

#install django
pip install django

#deactivate virtualenv
deactivate

#install postgres and necessary dependencies for django
sudo apt-get install libpq-dev python-dev -y
sudo apt-get install postgresql postgresql-contrib -y

#activate virtualenv
PS1="" source ../plates_env/bin/activate

#create postgres user and db, interactively
echo "Creating postgres user and database."
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw plates; then
  echo "Database 'plates' already exists, not replacing."
else
  sudo su - postgres -c "createdb plates"
fi

if sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='plates'" | grep -q 1; then 
  echo "User 'plates' already exists, not replacing."
else
  sudo su - postgres -c "createuser -P plates"
  psql -U postgres postgres <<INSTALLGRANTUSERPLATES
    GRANT ALL PRIVILEGES ON DATABASE plates TO plates;
INSTALLGRANTUSERPLATES
fi

#install psycopg2 to connect postgres and django
pip install psycopg2

#deactivate virtualenv
deactivate

echo "Completed installation successfully."
